"""initial

Revision ID: 7bf47582ffa5
Revises: 
Create Date: 2026-05-26 22:21:39.633427
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '7bf47582ffa5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_date', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('top_pain_ids', sa.Text(), nullable=True),
    sa.Column('new_pain_ids', sa.Text(), nullable=True),
    sa.Column('stats', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date')
    )
    op.create_table('pain_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('pain_score', sa.Float(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('source_post_ids', sa.Text(), nullable=True),
    sa.Column('source_comment_ids', sa.Text(), nullable=True),
    sa.Column('is_saas_idea', sa.Integer(), nullable=True),
    sa.Column('is_plugin_idea', sa.Integer(), nullable=True),
    sa.Column('business_angle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reddit_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('subreddit', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.Text(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reddit_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reddit_comment_id', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reddit_comment_id')
    )
    op.create_table('pain_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pain_point_id', sa.Integer(), nullable=False),
    sa.Column('emotion_intensity', sa.Float(), nullable=True),
    sa.Column('comment_volume', sa.Float(), nullable=True),
    sa.Column('repeat_frequency', sa.Float(), nullable=True),
    sa.Column('involves_money', sa.Float(), nullable=True),
    sa.Column('has_paid_solution', sa.Float(), nullable=True),
    sa.Column('automation_difficulty', sa.Float(), nullable=True),
    sa.Column('is_long_term', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pain_point_id'], ['pain_points.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pain_point_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pain_scores')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('pain_points')
    op.drop_table('daily_reports')
    # ### end Alembic commands ###
